# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WDxj_VNbgCRmZKrOF7VuesOIrLIZil9
"""

#Lazcano Flores Valeria
#Marban Ayala Catalina
#Sánchez Cruz Octavio Jesús


#Ejercicio 1: Crecimiento Exponencial
"""
Definición
Graficar los primeros 100 puntos de la ecuación en diferencias finitas Pn+1=k Pn
 con P0=2 y con:
• k=2
• k=1
• k=0.5
• k=−0.5
• k=−1
• k=−2

Delimitación
• Programar una ecuación en diferencias finitas.
• Repetir el proceso para todos los pesos.
• Crear las gráficas para todos los pesos.

Propuestas de solución
• Importar plt de matplotlib.pyplot para graficar.
• Crear una función con while o for para dar los puntos de la ecuación en dife-
  rencias finitas.
• Crear una lista que guarde todos los pesos y resolver la ecuación en diferencias
  finitas para cada peso de la lista.

Implementación
"""
import matplotlib.pyplot as plt
#Definimos una función de crecimiento exponencial con la ecuación en diferencias
#finitas Pn +1 = kPn con k costante.
def crecimiento_exponencial(k : float, n : int):
    Puntos = [2]

    for i in range(n):
      P = k * Puntos[-1]
      Puntos.append(P)

    return Puntos

#Asignamos los k que queremos ocupar.
pesos = [2, 1, 0.5, -0.5, -1, -2]
n = 100

#Para comprender mejor las ecucaciones en diferencias finitas mostramos una gráfica
#para cada uno de los pesos.
for k in pesos:
    Puntos = crecimiento_exponencial(k, n)
    plt.figure(figsize=(10,6))
    plt.plot(range(len(Puntos)), Puntos, label=f'k={k}')
    plt.title("Crecimiento Exponencial")
    plt.xlabel("n")
    plt.ylabel("P(n)")
    plt.legend()
    plt.grid()
    plt.show()

#Ejercicio 2: Crecimiento Logistico
"""
Definición
Reescribir la ecuación logistica vista en clases y graficar los primeros 40 puntos
de la ecucación en diferencias finitas del crecimiento logisitico con r = 0.5, k = 1000
y con P0:
• P0=5
• P0=1000
• P0=1500

Delimitación
• Programar una ecuación en diferencias finitas.
• Repetir el proceso para todss las poblaciones iniciales.
• Crear gráfica para todas las poblaciones iniciales.

Propuestas de solución
• Importar plt de matplotlib.pyplot para graficar.
• Crear una función con while o for para dar los puntos de la ecuación en dife-
  rencias finitas.
• Crear una lista que guarde todas las poblaciones iniciales y resolver la ecuación
  en diferencias finitas para cada peso de la lista.

Implementación
"""
import matplotlib.pyplot as plt
#Definimos una función de crecimiento logistica con la ecuación en diferencias finitas
#Pn+1 =kPn + r * Pn * (1 - (Pn / K)) con k y r costantes.
def crecimiento_logistico(P0 : int, r : float, K : float, n : int):
    P = [P0]

    for i in range(n):
      #Consideando Delta t = 1
        Pn_siguiente = P[-1] + r * P[-1] * (1 - (P[-1] / K))
        P.append(Pn_siguiente)

    return P

#Asignamos los valores y la lista con las poblaciones iniciales a evaluar.
r = 0.5
K = 1000
n = 40

Poblaciones_iniciales = [5, 1000, 1500]

plt.figure(figsize=(10,6))

#Mostramos las gráficas del crecimiento logistico con todas las poblaciones iniciales.
for P0 in Poblaciones_iniciales:
    P = crecimiento_logistico(P0, r, K, n)
    plt.plot(P, label=f'P0={P0}')
plt.title("Crecimiento Logístico")
plt.xlabel("n")
plt.ylabel("P(n)")
plt.legend()
plt.grid()
plt.show()

#Ejercicio 3: Crecimiento Lineal

"""Definición
Graficar los primeros 20 puntos de la ecuación en diferencias finitas Xn+1 = rXn+b
con los siguientes valores:
• r=0.5, b=2, X0=1
• r=1, b=1, X0=1
• r=1, b=0, X0=1
• r=2,b=2, X0=1

Delimitación
• Programar una ecuación en diferencias finitas.
• Repetir el proceso para todos los casos que se piden.
• Crear gráfica para totos los casos.

Propuestas de solución
• Importar plt de matplotlib.pyplot para graficar.
• Crear una función con while o for para dar los puntos de la ecuación en dife-
  rencias finitas.
• Crear una serie de listas que guarden la pendiente, el termino independiente y
 la inconita y resolver la ecuación en diferencias finitas para cada peso de la lista.

Implementación """

import matplotlib.pyplot as plt
#Definimos una función de crecimiento lineal con la ecuación en diferencias finitas
#Pn+1 =r*Xn + b con b y r costantes.

#Notemos que x0 es igual en todos los casos, entonces no lo consideramos
# r*X0 = r.
def ecuacion_lineal(r: float, b: float, n: int):
    X_list = [1]

    for i in range(n):
        P = r * X_list[-1] + b
        X_list.append(P)

    return X_list

n = 20
b_list = [2, 1, 0, 1]
r_list = [0.5, 1, 1, 2]

# Recorremos r y b correctamente y mostramos una gráfica para cada uno de los pesos.
for r, b in zip(r_list, b_list):
  plt.figure(figsize=(10,6))
  X_list = ecuacion_lineal(r, b, n)
  plt.plot(X_list, label=f'r={r}, b={b}')
  plt.title("Ecuación Lineal en Diferencias")
  plt.xlabel("n")
  plt.ylabel("X(n)")
  plt.legend()
  plt.grid()
  plt.show()

"""### Ejercicio 4"""

import numpy as np
import matplotlib.pyplot as plt

# Solución analítica: y(x) = -3x^2 + 3x + 2
def solucion_analitica(x):
    return -3 * x**2 + 3 * x + 2

# Diferencias finitas
def diferencias_finitas(dx, n_puntos):
    x_vals = [0.0]
    y_vals = [2.0]  # Condición inicial y(0) = 2

    for i in range(n_puntos - 1):
        x_i = x_vals[-1]
        y_i = y_vals[-1]

        # dy/dx = -6x + 3  =>  y_{i+1} = y_i + (-6*x_i + 3) * dx
        pendiente = -6 * x_i + 3
        y_siguiente = y_i + pendiente * dx
        x_siguiente = x_i + dx

        x_vals.append(x_siguiente)
        y_vals.append(y_siguiente)

    return np.array(x_vals), np.array(y_vals)

# Valores de delta del ejercicio
deltas = [0.5, 1, 5, 20]
n_puntos = 20

# figura con subplots
fig, axs = plt.subplots(2, 2, figsize=(12, 10))
axs = axs.flatten()

for i, dx in enumerate(deltas):
    # Calcula puntos por diferencias finitas
    x_fd, y_fd = diferencias_finitas(dx, n_puntos)

    # Genera curva analítica para el mismo rango de x
    x_rango = np.linspace(0, max(x_fd), 500)
    y_analitica = solucion_analitica(x_rango)

    # Grafica
    axs[i].plot(x_rango, y_analitica, label='Solución Analítica', color='blue', lw=2)
    axs[i].scatter(x_fd, y_fd, color='red', label=f'Diferencias Finitas (Δx={dx})', zorder=5)

    axs[i].set_title(f'Comparación con Δx = {dx}')
    axs[i].set_xlabel('x')
    axs[i].set_ylabel('y')
    axs[i].legend()
    axs[i].grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""Discusión de los Resultados:

Al observar las gráficas y el comportamiento de la aproximación, notamos que la aproximación sigue la curva, aunque se nota una ligera desviación acumulada conforme $x$ aumenta. A medida que $\Delta x$ aumenta (1, 5, 20), la distancia entre los puntos rojos y la línea azul se incrementa, ya que este método asume que la pendiente es constante durante todo el intervalo $\Delta x$. Como la solución real es una parábola, su pendiente cambia linealmente en cada punto. Al usar un paso muy grande (como $\Delta x = 20$), se pierde la información de la curvatura y en cada paso la aproximación se aleja un poco más de la solución real, lo que explica la diferencia al final de los 20 puntos en el eje $y$ para valores grandes de delta.
"""

import numpy as np
import matplotlib.pyplot as plt

def solucion_analitica(x):
    return -3 * x**2 + 3 * x + 2

def diferencias_finitas(dx, n_puntos):
    x_vals, y_vals = [0.0], [2.0]
    for i in range(n_puntos - 1):
        y_next = y_vals[-1] + (-6 * x_vals[-1] + 3) * dx
        x_vals.append(x_vals[-1] + dx)
        y_vals.append(y_next)
    return np.array(x_vals), np.array(y_vals)

# Parámetros para el Zoom
dx_zoom = 0.5
puntos_zoom = 6

x_fd, y_fd = diferencias_finitas(dx_zoom, puntos_zoom)
x_cont = np.linspace(0, max(x_fd), 200)
y_cont = solucion_analitica(x_cont)

plt.figure(figsize=(10, 6))
plt.plot(x_cont, y_cont, 'b-', label='Solución Analítica (Real)', lw=2)
plt.scatter(x_fd, y_fd, color='red', s=60, label=f'Diferencias Finitas ($\Delta x={dx_zoom}$)', zorder=5)

# Dibujar líneas de error para visualizar la diferencia
for i in range(len(x_fd)):
    y_real = solucion_analitica(x_fd[i])
    plt.vlines(x_fd[i], y_real, y_fd[i], colors='gray', linestyles='dashed', alpha=0.5)
    plt.text(x_fd[i], y_fd[i]+0.1, f'Error: {abs(y_fd[i]-y_real):.2f}', fontsize=9, ha='center')

plt.title('Zoom: Acumulación de Error en Diferencias Finitas')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

