# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mICCYpc2ySGK7xAbpM16cldDJdaK357t
"""

#Lazcano Flores Valeria
#Marban Ayala Catalina
#Sanchéz Cruz Octavio Jesús

import numpy as np
import matplotlib.pyplot as plt

def juego_del_caos(n_iter=10000):
    # Vértices del triángulo equilátero
    A = np.array([0, 0])
    B = np.array([1, 0])
    C = np.array([0.5, np.sqrt(3)/2])

    vertices = [A, B, C]

    #Punto cualquiera x0 dentro del plano
    try:
      x = float(input("Ingrese la coordenada x de su punto:"))
    except ValueError:
      print("Su valor no es válido.")
      print("Se considerará x = 0.25")
      x = 0.25

    try:
      y = float(input("Ingrese la coordenada y de su punto:"))
    except ValueError:
      print("Su valor no es válido.")
      print("Se considerará y = 0.25")
      y = 0.25

    p = np.array([x, y])

    # Lista para guardar los puntos
    puntos = []

    for elementos in range(n_iter):
        # Elegir de manera alaeatoria uno de los vertices
        r = np.random.uniform(0, 3)
        vertice = vertices[int(r)]

        # Punto medio
        p = (p + vertice) / 2
        puntos.append(p)

    return np.array(puntos)

# Ejecutar el algoritmo
puntos = juego_del_caos(10000)

# Grafica todos los puntos
plt.figure(figsize=(6, 6))
plt.scatter(puntos[:, 0], puntos[:, 1], s=0.5, color="black")
plt.axis("equal")
plt.show()

