# -*- coding: utf-8 -*-
"""Práctica03_TM1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ESUSHfvdXsVSsxgU1qHpnRd2P1U5MPLH

#Lazcano Flores Valeria
#Marban Ayala Catalina
#Sánchez Cruz Octavio Jesús
"""

#Ejercicio 1
"""
Definición
Completa la siguiente función de forma que calcule la cantidad de susceptibles, infectados y
removidos utilizando el sistema de ecuaciones en diferencias (2.0).

Posteriormente probar la función con los siguientes parámetros:
• S0 = 1000000
• I0 = 127
• R0 = 0
• alfa = 1
• beta = 0.6
• n = 150

Delimitación
• Programar una ecuación en diferencias finitas.
• Calcular la cantidad de infectados, suceptibles y removidos en la siguiente iteración.
• Crear graficas de lo anterior.

Propuestas de solución
• Importar plt de matplotlib.pyplot para graficar.
• Crear una función con while o for para dar los puntos de la ecuación en dife-
  rencias finitas.
• Dentro de la función, aplicar las fórmulas del documento para calcular el número
  de infectados, suceptibles y removidos en cada iteración.

Implementación
"""
import numpy as np
import matplotlib.pyplot as plt

def SIR(S0 : int, I0 : int, R0 : int, alfa : float, beta : float, n : int, Plot = True):
  N = S0 + I0 + R0
  S = [S0]
  I = [I0]
  R = [R0]

  for k in range(n-1):
    Sn = S[-1]
    In = I[-1]
    Rn = R[-1]

    S_siguiente = Sn - (alfa*Sn*In) / N
    I_siguiente = In + ((alfa*Sn*In) / N) - (beta * In)
    R_siguiente = Rn + (beta * In)

    S.append(S_siguiente)
    I.append(I_siguiente)
    R.append(R_siguiente)

  if Plot:
    plt.plot(range(0,n,1), S, 'm', label = 'S(n)')
    plt.plot(range(0,n,1), I, 'b', label = 'I(n)')
    plt.plot(range(0,n,1), R, 'g', label = 'R(n)')
    plt.legend()
    plt.xlabel('Tiempo (n)')
    plt.ylabel('Población')
    plt.title('Modelo SIR')
    plt.show()

  return (S, I, R)

S, I, R = SIR(S0 = 1000000, I0 = 127, R0 = 0, alfa = 1, beta = 0.6, n = 150)

#Ejercicio 2
"""
Definición
Utiliza la función que programaste en el ejercicio 2 para determinar el desarrollo de las
epidemias con los siguientes parámetros:

Caso 1:
• S0 = 100000
• I0 = 200000
• R0 = 0
• alfa = 0.7
• beta = 0.5
• n = 150

Caso 2:
• S0 = 200000
• I0 = 100000
• R0 = 0
• alfa = 0.75
• beta = 0.5
• n = 150

Caso 3:
• S0 = 1000000
• I0 = 10
• R0 = 0
• alfa = 0.75
• beta = 0.5
• n = 100

Delimitación
• Calcular la cantidad de infectados, suceptibles y removidos en la siguiente iteración.
• Crear graficas de lo anterior.

Propuestas de solución
Usar la funcion SIR(S0, I0, R0, alfa, beta, n, Plot = True) para cada caso.

Implementación
"""
S, I, R = SIR(S0 = 10000, I0 = 200000, R0 = 0, alfa = 0.7, beta = 0.5, n = 150)

S, I, R = SIR(S0 = 200000, I0 = 10000, R0 = 0, alfa = 0.75, beta = 0.5, n = 150)

S, I, R = SIR(S0 = 1000000, I0 = 10, R0 = 0, alfa = 0.75, beta = 0.5, n = 100)

#Ejercicio 3
"""
Definición
Para los casos del Ejercicio 2 calcula R0 utilizando la definición   R0 = alfa * S0 / N * beta
y argumenta como se relaciona este valor con el desarrollo de la epidemia.

Delimitación
• Calcular la cantidad de removidos inicial.
• Argumentar el porque se relacionan la cantidad de removidos con el desarrollo de la
  epidemia.
• Crear graficas de lo anterior.

Propuestas de solución
• Importar plt de matplotlib.pyplot para graficar.
• Crear dos funciones , la primera que calcule el valor de removidos incial y la segunda
  que grafique el desarollo de la epidemia.
• Evaluar para cada uno de los casos del ejercicio 2 y argumentar su relación.

Implementación
"""
import numpy as np
import matplotlib.pyplot as plt

def SIR(S0 : int, I0 : int, R0 : int, alfa : float, beta : float, n : int, Plot = True):
  N = S0 + I0 + R0
  S = [S0]
  I = [I0]
  R = [R0]

  for k in range(n-1):
    Sn = S[-1]
    In = I[-1]
    Rn = R[-1]

    S_siguiente = Sn - (alfa*Sn*In) / N
    I_siguiente = In + ((alfa*Sn*In) / N) - (beta * In)
    R_siguiente = Rn + (beta * In)

    S.append(S_siguiente)
    I.append(I_siguiente)
    R.append(R_siguiente)

  if Plot:
    plt.plot(range(0,n,1), S, 'm', label = 'S(n)')
    plt.plot(range(0,n,1), I, 'b', label = 'I(n)')
    plt.plot(range(0,n,1), R, 'g', label = 'R(n)')
    plt.legend()
    plt.xlabel('Tiempo (n)')
    plt.ylabel('Población')
    plt.title('Modelo SIR')
    plt.show()

  return (S, I, R)


def calcular_R0(S0, I0, R0, alfa, beta):
    N = S0 + I0 + R0
    x = (alfa * S0) / (beta * N)
    return x

casos = [
    (100000, 200000, 0, 0.7, 0.5, 150),
    (200000, 100000, 0, 0.75, 0.5, 150),
    (1000000, 10, 0, 0.75, 0.5, 100)
]

for caso in casos:
    S0, I0, R0, alfa, beta, n = caso
    R0 = calcular_R0(S0, I0, R0, alfa, beta)
    print(f"R0 = {R0:.3f}")
    SIR(S0, I0, R0, alfa, beta, n)

"""
Relación de R0 con el desarrollo de la epidemia

Notemos que:
In+1 - In = [(In * alfa * Sn) / N] - beta * In

Entonces:
In+1 - In = In[({alfa * Sn}/N) - beta]

Dividiendo todo entre beta
(In+1 - In)/beta = In[({alfa * Sn}/N) - beta] / beta = In[{alfa * Sn}/N*beta) - 1]

Recordando que R0 = alfa * S0 / N * beta y evaluando en S0 tenemos que:
(In+1 - In)/beta = In(R0 - 1)

Dle lo anterior tenemos que In+1 - In es positiva si R0 > 1, es decir, el número de infectados
crece si R0 es mayor a uno; In+1 - In es negativa si R0 < 1 es decir, el número de infectados
decrece si R0 es menor que uno.
"""